services:
  shelly-manager-admin:
    build: .
    container_name: shelly-manager-admin
    restart: unless-stopped
    ports:
      - "${HOST_PORT}:5000"
    volumes:
      - ${APP_DB_PATH}:/app/data
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - FLASK_ENV=${FLASK_ENV}
